[package]
name = "fae-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb="2.5.0"
amqprs="1.3.0"
serde_json="1.0.96"
regex="1.8.1"